### ISSUE TITLE
Taking suggestions for a more simplified yet very flexible syntax

### ISSUE THREAD

**Issue by MatteuSan** [SurPathHub/ugnay-components-web#1]
The current syntax ugnay has is (in my opinion) not very well thought out. Relies on SCSS variables instead of CSS custom properties for the colors, has a mixin-reliant syntax - to which I think frightens most people who don't know SCSS very well. We basically need a syntax that implements the design system SurPath Hub has, yet lets the user have the power to change a few elements in there, like colors, typography, and shape, without relying on utility classes and/or atomic CSS.

**Comment by MatteuSan** [comment]
To add: I am also doing my part in this, but I also figured that the community might have a better approach to this

**Comment by MatteuSan** [comment]
I can't really move on with the development without determining the syntax to be used for the library. So here are two ideas I have as of now:

1. Current:
```scss
// Call the mixin that generates the styles
@include SPHButton.use(
  // Configure the SPHButton theme with this parameter/map
  $theme: (
    'light': #hex-color,
    'default': #hex-color,
    'dark': #hex-color,
    'ink': #hex-color,
    'elevation': #hex-color,
  )
);
```
Pros:
- Not redundant
- Highly configurable/flexible (in terms of color theme)

Cons:
- Super verbose (imo), might scare the beginner developers.
- Can result to a bloated CSS file if not used properly.

2. Using @extend:
```scss
.my-button-class {
   // Sets the button theme for this specific class.
   --button-fill: #hex-color;
   --button-ink: #hex-color;
   --button-elevation: #hex-color;

   // Alternatively, we can also do it with SCSS variables.
   $button-fill: #hex-color;
   $button-ink: #hex-color;
   $button-elevation: #hex-color;

   // Render the design system implementation. This in turn will also apply the theme you set.
   @extend %sph-button
}
```
Pros:
- Highly configurable/flexible
- Simple syntax, very beginner-friendly
- Will have a more condensed CSS file output

Cons:
- Theme application will be super redundant


If y'all have any other ideas for another syntax, please feel free to drop them here :>>>


PS: #hex-color can also be rgb, rgba, hsl, etc. Pick your poison basically :>
